name: Firestore Security Rules Test

on:
  workflow_dispatch:

jobs:
  test_firestore_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Set up Firebase CLI
        run: npm install -g firebase-tools

      - name: Start Firebase Emulators
        run: firebase emulators:start --only firestore &

      - name: Wait for Firestore Emulator
        run: |
          for i in {1..30}; do
            nc -z localhost 8080 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Firestore Emulator
          exit 1

      - name: Run Jest tests
        run: npm run test
