name: Pull Firestore Index
on:
  workflow_dispatch:
jobs:
  pull-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Firebase CLI
        run: |
          sudo npm install -g firebase-tools

      - name: Set active Firebase project
        run: |
          firebase use development  --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Pull Firestore Index
        run: |
          firebase firestore:indexes > "$(cat firebase.json | jq -r '.firestore.indexes')"\
            --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Set branch name with date
        run: |
          branch_name="pull-firestore-index-$(date +'%Y%m%d-%H%M%S')"
          echo ::set-output name=branch::$branch_name
        id: branch

      - name: Git Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b ${{ steps.branch.outputs.branch }}
          git add .
          git commit -m "${{ steps.branch.outputs.branch }}"
          git push